<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageVersion Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.9" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.2" />
    <PackageVersion Include="Polly.Contrib.WaitAndRetry" Version="1.1.1" />
    <PackageVersion Include="Polly" Version="8.6.5" />
    <PackageVersion Include="Refit.HttpClientFactory" Version="9.0.2" />
    <PackageVersion Include="Refit" Version="9.0.2" />
    <PackageVersion Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.1.0" />
    <PackageVersion Include="Teraa.IrcMessageParser" Version="3.0.0" />
  </ItemGroup>
</Project>
