<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Teraa.Twitch.EventSub</AssemblyName>
    <RootNamespace>Teraa.Twitch.EventSub</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ws\Ws.csproj" />
  </ItemGroup>

</Project>
